version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: frontend-vue/Dockerfile
    container_name: frontend
    ports:
      - "4173:4173"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge