name: Frontend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Укажите версию Node.js 18 или выше

    - name: Install dependencies
      run: |
        cd frontend-vue
        npm install

    - name: Build project
      run: |
        cd frontend-vue
        npm run build

    - name: Run tests
      run: |
        cd frontend-vue
        npm test
